import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

const bib500 = {
  'BIB500-D-000': [
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LIG0285',
      'Variant Code': '',
      Description: 'selfCheck500 - 5V+ USB RGB LED strip',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LOC0115',
      'Variant Code': '',
      Description: 'S Lite Kiosk lock Key no. R31003 (18x12mm)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MON0115',
      'Variant Code': '',
      Description: 'iiyama ProLite T2235MSC-B1 55.9 cm (22)LCD Digital',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0105',
      'Variant Code': '',
      Description: 'ss400 Direct thermal print roll',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0195',
      'Variant Code': '',
      Description: 'Fujitsu FP -1000 80mm printer (no alternative)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0106',
      'Variant Code': '',
      Description: 'RFID Reader usb -ID ISC.MRM102-USB MRR',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0540',
      'Variant Code': '',
      Description: 'Unified Kiosk Antenna,shielded assembly ss200,-103',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TAP0135',
      'Variant Code': '',
      Description: 'RS Pro Black Single Sided Foam Tape, EPDM, 1 reel',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1035',
      'Variant Code': '',
      Description: 'Lindy 4 Port USB 2.0 Cable Hub, Micro-B',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'VEL0105',
      'Variant Code': '',
      Description: 'VELCRO® brand 24 pairs Stick-on squares 25mm box o',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': '011-007-EL001',
      'Variant Code': '',
      Description: 'SC500 KIT',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'A',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB1005',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500™ - Acrylic overlay',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'ACR0455',
      'Variant Code': '',
      Description: 'selfCheck™ 500 - Book acrylic',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'BAR0165',
      'Variant Code': '',
      Description: '1D Barcode scanner Gryphon GFS 4170 Fixed scanner,',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BIB500-USER-PK-001',
      'Variant Code': '',
      Description: 'selfCheck™ 500 - User guide pack',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0196',
      'Variant Code': '',
      Description: 'IEC inlet SCHAFFNER-FN284-6-06-FILTER, 6a (no alte',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0415',
      'Variant Code': '',
      Description: 'C13 to C5 UL Conversion adapter',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CPU0695',
      'Variant Code': '',
      Description: 'COMPUTER HP MP9 G4 i3 PC Bib Spec  ',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0760',
      'Variant Code': '',
      Description: 'Brass round spacer 6mm',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 4,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0965',
      'Variant Code': '',
      Description: 'selfCheck500 - Rubber stops',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0985',
      'Variant Code': '',
      Description: 'selfCheck500 - Side blanking grommet 32mm black (1',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0990',
      'Variant Code': '',
      Description: 'selfCheck500 - Blanking plug 16mm black',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX1005',
      'Variant Code': '',
      Description: 'Fir Tree Plugs',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FUS0100',
      'Variant Code': '',
      Description: '5a Fuse for iec inlet',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'IDMR11040',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - Desktop fixing list',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0120',
      'Variant Code': '',
      Description: 'Elec warning label (pack of 100)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0715',
      'Variant Code': '',
      Description: '30 CM RJ45 M/F Shield Eth N/work Sc/Panel Mount Ex',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1000',
      'Variant Code': '',
      Description: 'DisplayPort Male Plug to Plug Video Cable GOLD 1m',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LIG0285',
      'Variant Code': '',
      Description: 'selfCheck500 - 5V+ USB RGB LED strip',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LOC0115',
      'Variant Code': '',
      Description: 'S Lite Kiosk lock Key no. R31003 (18x12mm)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MON0115',
      'Variant Code': '',
      Description: 'iiyama ProLite T2235MSC-B1 55.9 cm (22)LCD Digital',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0105',
      'Variant Code': '',
      Description: 'ss400 Direct thermal print roll',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0195',
      'Variant Code': '',
      Description: 'Fujitsu FP -1000 80mm printer (no alternative)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0106',
      'Variant Code': '',
      Description: 'RFID Reader usb -ID ISC.MRM102-USB MRR',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0540',
      'Variant Code': '',
      Description: 'Unified Kiosk Antenna,shielded assembly ss200,-103',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TAP0135',
      'Variant Code': '',
      Description: 'RS Pro Black Single Sided Foam Tape, EPDM, 1 reel',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1035',
      'Variant Code': '',
      Description: 'Lindy 4 Port USB 2.0 Cable Hub, Micro-B',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'VEL0105',
      'Variant Code': '',
      Description: 'VELCRO® brand 24 pairs Stick-on squares 25mm box o',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': '011-007-EL001',
      'Variant Code': '',
      Description: 'selfCheck™ 500 - Electrical kit',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB1005',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500™ - Acrylic overlay',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'B',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MAG0150',
      'Variant Code': '',
      Description: '10mm dia x 5mm Samarium Cobalt Magnet - 1.4kg Pull',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'C',
      Status: 'Certified',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BSUB0005',
      'Variant Code': '',
      Description: 'selfCheck™ 500 - Core components',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'C',
      Status: 'Certified',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BSUB0009',
      'Variant Code': '',
      Description: 'selfCheck™ 500 - HF 13.56 Mhz',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'C',
      Status: 'Certified',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MON0115',
      'Variant Code': '',
      Description: 'iiyama ProLite T2235MSC-B1 55.9 cm (22)LCD Digital',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0540',
      'Variant Code': '',
      Description: 'Unified Kiosk Antenna,shielded assembly ss200,-103',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0106',
      'Variant Code': '',
      Description: 'RFID Reader usb -ID ISC.MRM102-USB MRR',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0195',
      'Variant Code': '',
      Description: 'Fujitsu FP -1000 80mm printer (no alternative)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0105',
      'Variant Code': '',
      Description: 'ss400 Direct thermal print roll',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0105',
      'Variant Code': '',
      Description: 'USB 1mtr A-B (printer) (CDL-101)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FUS0100',
      'Variant Code': '',
      Description: '5a Fuse for iec inlet',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0915',
      'Variant Code': '',
      Description: 'selfCheck500 - 240V power loom',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'BAR0165',
      'Variant Code': '',
      Description: '1D Barcode scanner Gryphon GFS 4170 Fixed scanner,',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0115',
      'Variant Code': '',
      Description: 'Primary earth label (roll of 500)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0120',
      'Variant Code': '',
      Description: 'Elec warning label (pack of 100)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LOC0115',
      'Variant Code': '',
      Description: 'S Lite Kiosk lock Key no. R31003 (18x12mm)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'VEL0105',
      'Variant Code': '',
      Description: 'VELCRO® brand 24 pairs Stick-on squares 25mm box o',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'ACR0455',
      'Variant Code': '',
      Description: 'selfCheck500 - Book acrylic',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0445',
      'Variant Code': '',
      Description: 'ss1000 PRI cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0910',
      'Variant Code': '',
      Description: 'selfCheck500 - Printer + RFID accessory cable',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0455',
      'Variant Code': '',
      Description: 'ss1000 BAR cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0715',
      'Variant Code': '',
      Description: '30 CM RJ45 M/F Shield Eth N/work Sc/Panel Mount Ex',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0435',
      'Variant Code': '',
      Description: 'ss1000 RFID cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0965',
      'Variant Code': '',
      Description: 'selfCheck500 - Rubber stops',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0430',
      'Variant Code': '',
      Description: 'ss1000 IO cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0970',
      'Variant Code': '',
      Description: 'selfCheck500 - M4 rubber feet (bag of 10)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0425',
      'Variant Code': '',
      Description: 'ss1000 SCR cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LIG0285',
      'Variant Code': '',
      Description: 'selfCheck500 - 5V+ USB RGB LED strip',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0760',
      'Variant Code': '',
      Description: 'Brass round spacer 6mm',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 4,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0990',
      'Variant Code': '',
      Description: 'selfCheck500 - Blanking plug 16mm black',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0985',
      'Variant Code': '',
      Description: 'selfCheck500 - Side blanking grommet 32mm black (1',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1000',
      'Variant Code': '',
      Description: 'DisplayPort Male Plug to Plug Video Cable GOLD 1m',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0196',
      'Variant Code': '',
      Description: 'IEC inlet SCHAFFNER-FN284-6-06-FILTER, 6a (no alte',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'UPM0120',
      'Variant Code': '',
      Description: 'HUB, USB2.0, 4 PORT CABLE STYLE(debs)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX1005',
      'Variant Code': '',
      Description: 'Fir Tree Plugs',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CHA0120',
      'Variant Code': '',
      Description: 'SC500 - Printer door strain relief',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB1005',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500™ - Acrylic overlay',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0415',
      'Variant Code': '',
      Description: 'C13 to C5 UL Conversion adapter',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TIE0180',
      'Variant Code': '',
      Description: 'Helawrap UL cable management (25 meters)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TAP0135',
      'Variant Code': '',
      Description: 'RS Pro Black Single Sided Foam Tape, EPDM, 1 reel',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'IDMR11040',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - Desktop fixing list',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BIB500-USER-PK-001',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - User guide pack',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1075',
      'Variant Code': '',
      Description: 'USB Extension Cable Male USB A to Female USB A 25c',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V1',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CPU0550',
      'Variant Code': '',
      Description: 'Computer, HP MP9 FreeDOS without image',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MON0115',
      'Variant Code': '',
      Description: 'iiyama ProLite T2235MSC-B1 55.9 cm (22)LCD Digital',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0540',
      'Variant Code': '',
      Description: 'Unified Kiosk Antenna,shielded assembly ss200,-103',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0106',
      'Variant Code': '',
      Description: 'RFID Reader usb -ID ISC.MRM102-USB MRR',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0195',
      'Variant Code': '',
      Description: 'Fujitsu FP -1000 80mm printer (no alternative)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0105',
      'Variant Code': '',
      Description: 'ss400 Direct thermal print roll',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0105',
      'Variant Code': '',
      Description: 'USB 1mtr A-B (printer) (CDL-101)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FUS0100',
      'Variant Code': '',
      Description: '5a Fuse for iec inlet',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0915',
      'Variant Code': '',
      Description: 'selfCheck500 - 240V power loom',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'BAR0165',
      'Variant Code': '',
      Description: '1D Barcode scanner Gryphon GFS 4170 Fixed scanner,',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0115',
      'Variant Code': '',
      Description: 'Primary earth label (roll of 500)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0120',
      'Variant Code': '',
      Description: 'Elec warning label (pack of 100)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LOC0115',
      'Variant Code': '',
      Description: 'S Lite Kiosk lock Key no. R31003 (18x12mm)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'VEL0105',
      'Variant Code': '',
      Description: 'VELCRO® brand 24 pairs Stick-on squares 25mm box o',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'ACR0455',
      'Variant Code': '',
      Description: 'selfCheck500 - Book acrylic',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0445',
      'Variant Code': '',
      Description: 'ss1000 PRI cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0910',
      'Variant Code': '',
      Description: 'selfCheck500 - Printer + RFID accessory cable',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0455',
      'Variant Code': '',
      Description: 'ss1000 BAR cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0715',
      'Variant Code': '',
      Description: '30 CM RJ45 M/F Shield Eth N/work Sc/Panel Mount Ex',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0435',
      'Variant Code': '',
      Description: 'ss1000 RFID cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0965',
      'Variant Code': '',
      Description: 'selfCheck500 - Rubber stops',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0430',
      'Variant Code': '',
      Description: 'ss1000 IO cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0970',
      'Variant Code': '',
      Description: 'selfCheck500 - M4 rubber feet (bag of 10)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0425',
      'Variant Code': '',
      Description: 'ss1000 SCR cable label',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LIG0285',
      'Variant Code': '',
      Description: 'selfCheck500 - 5V+ USB RGB LED strip',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0760',
      'Variant Code': '',
      Description: 'Brass round spacer 6mm',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 4,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0990',
      'Variant Code': '',
      Description: 'selfCheck500 - Blanking plug 16mm black',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0985',
      'Variant Code': '',
      Description: 'selfCheck500 - Side blanking grommet 32mm black (1',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1000',
      'Variant Code': '',
      Description: 'DisplayPort Male Plug to Plug Video Cable GOLD 1m',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0196',
      'Variant Code': '',
      Description: 'IEC inlet SCHAFFNER-FN284-6-06-FILTER, 6a (no alte',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX1005',
      'Variant Code': '',
      Description: 'Fir Tree Plugs',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CHA0120',
      'Variant Code': '',
      Description: 'SC500 - Printer door strain relief',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB1005',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500™ - Acrylic overlay',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 0,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0415',
      'Variant Code': '',
      Description: 'C13 to C5 UL Conversion adapter',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TIE0180',
      'Variant Code': '',
      Description: 'Helawrap UL cable management (25 meters)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TAP0135',
      'Variant Code': '',
      Description: 'RS Pro Black Single Sided Foam Tape, EPDM, 1 reel',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 0.3,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'IDMR11040',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - Desktop fixing list',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BIB500-USER-PK-001',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - User guide pack',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0101',
      'Variant Code': '',
      Description: 'EU Mains power cable - straight IEC female - 3m',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1150',
      'Variant Code': '',
      Description: '3M Mains IEC (C13) – US (UL APPROVED)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0290',
      'Variant Code': '',
      Description: 'Lindy 4 Port USB Hub (google) No.42836',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0100',
      'Variant Code': '',
      Description: 'UK Mains power cable - straight IEC female - 3m (R',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V2',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CPU0550',
      'Variant Code': '',
      Description: 'Computer, HP MP9 FreeDOS without image',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'ACR0455',
      'Variant Code': '',
      Description: 'selfCheck500 - Book acrylic',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'BAR0165',
      'Variant Code': '',
      Description: '1D Barcode scanner Gryphon GFS 4170 Fixed scanner,',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'BIB500-USER-PK-001',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - User guide pack',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0196',
      'Variant Code': '',
      Description: 'IEC inlet SCHAFFNER-FN284-6-06-FILTER, 6a (no alte',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CON0415',
      'Variant Code': '',
      Description: 'C13 to C5 UL Conversion adapter',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'CPU0550',
      'Variant Code': '',
      Description: 'Computer, HP MP9 FreeDOS without image',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0760',
      'Variant Code': '',
      Description: 'Brass round spacer 6mm',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 4,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0965',
      'Variant Code': '',
      Description: 'selfCheck500 - Rubber stops',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0985',
      'Variant Code': '',
      Description: 'selfCheck500 - Side blanking grommet 32mm black (1',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX0990',
      'Variant Code': '',
      Description: 'selfCheck500 - Blanking plug 16mm black',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FIX1005',
      'Variant Code': '',
      Description: 'Fir Tree Plugs',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 6,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'FUS0100',
      'Variant Code': '',
      Description: '5a Fuse for iec inlet',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Production BOM',
      'No.': 'IDMR11040',
      'Variant Code': '',
      Description: 'Bibliotheca selfCheck 500 - Desktop fixing list',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LAB0120',
      'Variant Code': '',
      Description: 'Elec warning label (pack of 100)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA0715',
      'Variant Code': '',
      Description: '30 CM RJ45 M/F Shield Eth N/work Sc/Panel Mount Ex',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 2,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1000',
      'Variant Code': '',
      Description: 'DisplayPort Male Plug to Plug Video Cable GOLD 1m',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LIG0285',
      'Variant Code': '',
      Description: 'selfCheck500 - 5V+ USB RGB LED strip',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LOC0115',
      'Variant Code': '',
      Description: 'S Lite Kiosk lock Key no. R31003 (18x12mm)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MET0315',
      'Variant Code': '',
      Description: 'SMARTSERVE - Mid-range desktop',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'MON0115',
      'Variant Code': '',
      Description: 'iiyama ProLite T2235MSC-B1 55.9 cm (22)LCD Digital',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0105',
      'Variant Code': '',
      Description: 'ss400 Direct thermal print roll',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'PRI0195',
      'Variant Code': '',
      Description: 'Fujitsu FP -1000 80mm printer (no alternative)',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0106',
      'Variant Code': '',
      Description: 'RFID Reader usb -ID ISC.MRM102-USB MRR',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'RFI0540',
      'Variant Code': '',
      Description: 'Unified Kiosk Antenna,shielded assembly ss200,-103',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'TAP0135',
      'Variant Code': '',
      Description: 'RS Pro Black Single Sided Foam Tape, EPDM, 1 reel',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'LEA1035',
      'Variant Code': '',
      Description: 'Lindy 4 Port USB 2.0 Cable Hub, Micro-B',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': 'VEL0105',
      'Variant Code': '',
      Description: 'VELCRO® brand 24 pairs Stick-on squares 25mm box o',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
    {
      'Version Code': 'V3',
      Status: 'Closed',
      'Starting Date': '',
      'Ending Date': '',
      Type: 'Item',
      'No.': '011-007-EL001',
      'Variant Code': '',
      Description: 'SC500 KIT',
      'Unit of Measure Code': 'PCS',
      'Quantity per': 1,
    },
  ],
};

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
